### ISSUE TITLE
Apple Screen Issues

### ISSUE THREAD

**Issue by panquemao** [ZhengLinLei/stackblock.io#56]
In safari:
![IMG_6650](https://github.com/ZhengLinLei/stackblock.io/assets/116371763/3f4bf962-db87-4870-9ba4-9697d8b013cd)
![IMG_6651](https://github.com/ZhengLinLei/stackblock.io/assets/116371763/3f2f05f7-26a0-4296-b56a-ea22579a506d)

In the app:
![IMG_6652](https://github.com/ZhengLinLei/stackblock.io/assets/116371763/be0e8840-38dd-4f3b-bb33-aacf1d3e54c9)
![IMG_6653](https://github.com/ZhengLinLei/stackblock.io/assets/116371763/5b55e7c9-2e60-4952-8145-f67feace12fe)
![IMG_6654](https://github.com/ZhengLinLei/stackblock.io/assets/116371763/0378df94-52c3-4d67-807f-0ea35a135cdd)

**Comment by ZhengLinLei** [comment]
Canvas resize and iPhone safe area problem

**Comment by ZhengLinLei** [comment]
Hard fixed meta data `theme-color`

**Comment by ZhengLinLei** [comment]
Top fixed

<img width="516" alt="Screenshot 2023-10-21 at 00 51 49" src="https://github.com/ZhengLinLei/stackblock.io/assets/77938581/8515894b-989c-4d39-88ed-ecb63de91a63">

**Comment by ZhengLinLei** [comment]
Reopen this issue because is not working correctly

<img width="512" alt="Screenshot 2023-10-25 at 23 28 39" src="https://github.com/ZhengLinLei/stackblock.io/assets/77938581/fe8357bd-6638-4467-80b7-adfb532bbe42">

**Comment by ZhengLinLei** [comment]
New Logic:

* `viewport-fit=contain` in viewport html
*  Change it to `viewport-fit=cover` if user rotate the phone.
*  Change body bg color in `changeBackground`
